FROM tindy2013/subconverter:latest
RUN sed -i '/TW/s/🇨🇳/🇹🇼/g' /base/snippets/emoji.txt && \
    sed -i '/TW/{n;s/🇨🇳/🇹🇼/g;}' /base/snippets/emoji.toml
RUN apk --update add tzdata && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    rm -rf /var/cache/apk/*

COPY scripts\crontab /tmp
RUN apk add git && \
    cd /base/rules && \
    git clone git@github.com:pengfujin-momo/myself.git
RUN cat /tmp/crontab >> /var/spool/cron/crontabs/root && \
    rm -rf /tmp/* 
EXPOSE 25500
WORKDIR /base
CMD crond && subconverter
