FROM tindy2013/subconverter:0.7.2


COPY replacements/snippets/emoji.toml /base/snippets/emoji.toml
COPY replacements/snippets/emoji.txt /base/snippets/emoji.txt

RUN apk --update add tzdata && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone

EXPOSE 25500
